version: '3.3'

services:
  vpn-config-tester:
    container_name: configtest
    volumes:
      - ./data/:/tmp/data
      - ./tmp/:/test_tmp
      - ./openvpn:/etc/openvpn:ro
      - ./provider_test.py:/app/provider_test.py:ro
    logging:
      driver: json-file
      options:
        max-size: 10m
    image: arsscriptum/transmission-openvpn:latest
    command: |
      sh -c "pip install python-dotenv && python3 -u /app/provider_test.py"

